#
# Changes to this file will be overwritten by `trmnlp pull`.
#
# Docs: https://help.trmnl.com/en/articles/10542599-importing-and-exporting-private-plugins#h_581fb988f0
#
# Working; 'https://opendata-download-metfcst.smhi.se/api/category/snow1g/version/1/geotype/point/lon/11.974560/lat/57.708870/data.json'
---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: 'https://opendata-download-metfcst.smhi.se/api/category/snow1g/version/1/geotype/point/lon/{{longitude}}/lat/{{latitude}}/data.json'
polling_headers: ''
name: SMHI Weather
custom_fields:
- keyname: city
  field_type: string
  placeholder: Gothenburg
  name: City
- keyname: latitude
  field_type: string
  placeholder: '59.4'
  name: Latitude
- keyname: longitude
  field_type: string
  placeholder: '18.5'
  name: Longitude
- keyname: forecast_count
  field_type: int
  placeholder: 7
  name: Number of hourly forecasts to display
- keyname: forecast_hours
  field_type: string
  placeholder: "06,12,16,20"
  name: Comma-separated list of hours (24h) to include in forecast
refresh_interval: 1440
